# Generated by Django 3.0.8 on 2020-07-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200710_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverification',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
